# action.yml
name: 'Cargo + Zig'
description: 'Build with Cargo + Zig'
inputs:
  command:
    description: 'Cargo subcommand to execute (excluding --target)'
    required: true
  target:
    description: 'Cargo target'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target }}
    - ${{ inputs.command }}