#!/bin/bash

TARGET="$1"

shift

ZIG_COMMAND="zig cc -target ${ZIG_TARGET}"

export CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER="${ZIG_COMMAND}"
export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER="${ZIG_COMMAND}"
export CC="${ZIG_COMMAND}"

cargo $@ "--target=${TARGET}"