name: Build & Push Enclaver Wrapper Base Container

on:
  push:
    branches:
      - main

jobs:
  build-enclaver-wrapper-base:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/77991489452/locations/global/workloadIdentityPools/gh-actions-identity-pool/providers/gh-actions-identity-provider'
          service_account: 'github-actions-service-account@edgebit-containers.iam.gserviceaccount.com'
      - name: Configure Docker Auth
        run: |
          gcloud auth configure-docker us-docker.pkg.dev
      - name: Build Enclaver Wrapper Base Image
        uses: docker/build-push-action@v3
        with:
          file: builder/dockerfiles/runtimebase.dockerfile
          platforms: linux/amd64
          push: true
          tags: us-docker.pkg.dev/edgebit-containers/containers/enclaver-wrapper-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max