name: Rust CI

on:
  push

jobs:
  build-release-binaries:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cargo-zig
        with:
          target: 'x86_64-unknown-linux-musl'
          command: 'build --frozen --manifest-path enclaver/Cargo.toml'
