name: CI

on: [push, pull_request]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Install the MSRV toolchain and clippy
      - run: sed -n 's/^rust-version = "\(.*\)"$/RUSTUP_TOOLCHAIN=\1/p' enclaver/Cargo.toml >> $GITHUB_ENV
      - run: rustup toolchain install $RUSTUP_TOOLCHAIN
      - run: rustup component add clippy

      # Check with --all-features (ie a Linux build)
      - uses: actions-rs/clippy@master
        with:
          args: --all-features --manifest-path enclaver/Cargo.toml

      # Check with only default features (ie a Mac build)
      - uses: actions-rs/clippy@master
        with:
          args: --manifest-path enclaver/Cargo.toml


  ## TODO: Add test job here?
