name: Rust CI

on:
  push

jobs:
  build-release-binaries:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      matrix:
        build-target: ['x86_64-unknown-linux-musl']

    steps:
      - uses: actions/checkout@v3
      - name: Build Release Binaries
        uses: ./.github/actions/cargo-zigbuild
        with:
          target: ${{ matrix.build-target }}
          args: '--manifest-path enclaver/Cargo.toml --release'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.build-target }}
          path: |
            enclaver/target/${{ matrix.build-target }}/release/enclaver
            enclaver/target/${{ matrix.build-target }}/release/odyn
