name: Rust CI

on:
  push

jobs:
  build-nitro-cli:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/77991489452/locations/global/workloadIdentityPools/gh-actions-identity-pool/providers/gh-actions-identity-provider'
          service_account: 'github-actions-service-account@edgebit-containers.iam.gserviceaccount.com'
      - name: Configure Docker Auth
        run: |
          gcloud auth configure-docker us-docker.pkg.dev
      - name: Build Release Artifacts
        uses: docker/build-push-action@v3
        with:
          file: builder/dockerfiles/build-release.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: us-docker.pkg.dev/edgebit-containers/containers/release
